apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: order-service
  name: order-service
  namespace: kailash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: "order-service:1.0"
