apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: shipping-service
  name: shipping-service
  namespace: kailash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
        - name: shipping-service
          image: "shipping-service:1.0"
