apiVersion: v1
kind: Service
metadata:
    name: inventory-service
    namespace: kailash
spec:
    type: NodePort
    ports:
        -
            port: 9200
            targetPort: 9200
            nodePort: 30200
    selector:
        app: inventory-service
